spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/spring?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: root
    password:
    driverClassName: com.mysql.jdbc.Driver
    jpa:
      defer-datasource-initialization: true
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  h2:
    console:
      settings:
        web-allow-others: true
      enabled: true
      path: /db
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect
